import type { Config } from 'tailwindcss';
import animate from 'tailwindcss-animate';

const config: Config = {
  darkMode: ['class'],
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    container: {
      center: true,
      padding: { DEFAULT: '1.25rem', sm: '1.5rem', lg: '2rem' },
      screens: { '2xl': '1200px' },
    },
    extend: {
      colors: {
        // ── Deep Violet (primary brand) ──
        brand: {
          50:  '#f5f3ff',
          100: '#ede9fe',
          200: '#ddd6fe',
          300: '#c4b5fd',
          400: '#a78bfa',
          500: '#8b5cf6',
          600: '#7c3aed',
          700: '#6d28d9',
          800: '#5b21b6',
          900: '#4c1d95',
          950: '#2e1065',
        },
        // ── maroon kept as alias so old references still compile ──
        maroon: {
          50:  '#f5f3ff',
          100: '#ede9fe',
          200: '#ddd6fe',
          300: '#c4b5fd',
          400: '#a78bfa',
          500: '#8b5cf6',
          600: '#7c3aed',
          700: '#6d28d9',
          800: '#5b21b6',
          900: '#4c1d95',
          950: '#2e1065',
        },
        // ── Amber Gold ──
        gold: {
          50:  '#fffbeb',
          100: '#fef3c7',
          200: '#fde68a',
          300: '#fcd34d',
          400: '#fbbf24',
          500: '#f59e0b',
          600: '#d97706',
          700: '#b45309',
          800: '#92400e',
          900: '#78350f',
        },
        // ── Subtle violet-tinted surfaces ──
        cream: {
          50:  '#ffffff',
          100: '#fdfcff',
          200: '#f5f3ff',
          300: '#ede9fe',
          400: '#ddd6fe',
          500: '#c4b5fd',
          600: '#a78bfa',
        },
        background:   'hsl(var(--background))',
        foreground:   'hsl(var(--foreground))',
        card:         { DEFAULT: 'hsl(var(--card))',        foreground: 'hsl(var(--card-foreground))' },
        popover:      { DEFAULT: 'hsl(var(--popover))',     foreground: 'hsl(var(--popover-foreground))' },
        primary:      { DEFAULT: 'hsl(var(--primary))',     foreground: 'hsl(var(--primary-foreground))' },
        secondary:    { DEFAULT: 'hsl(var(--secondary))',   foreground: 'hsl(var(--secondary-foreground))' },
        muted:        { DEFAULT: 'hsl(var(--muted))',       foreground: 'hsl(var(--muted-foreground))' },
        accent:       { DEFAULT: 'hsl(var(--accent))',      foreground: 'hsl(var(--accent-foreground))' },
        destructive:  { DEFAULT: 'hsl(var(--destructive))', foreground: 'hsl(var(--destructive-foreground))' },
        border: 'hsl(var(--border))',
        input:  'hsl(var(--input))',
        ring:   'hsl(var(--ring))',
      },
      fontFamily: {
        display: ['Playfair Display', 'Georgia', 'serif'],
        heading: ['Cormorant Garamond', 'Georgia', 'serif'],
        body:    ['Inter', 'system-ui', 'sans-serif'],
        sans:    ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'display-2xl': ['4.5rem',  { lineHeight: '1.05', letterSpacing: '-0.025em', fontWeight: '700' }],
        'display-xl':  ['3.75rem', { lineHeight: '1.08', letterSpacing: '-0.02em',  fontWeight: '700' }],
        'display-lg':  ['3rem',    { lineHeight: '1.1',  letterSpacing: '-0.02em',  fontWeight: '700' }],
        'display-md':  ['2.25rem', { lineHeight: '1.15', letterSpacing: '-0.015em', fontWeight: '600' }],
        'display-sm':  ['1.875rem',{ lineHeight: '1.2',  fontWeight: '600' }],
        'display-xs':  ['1.5rem',  { lineHeight: '1.3',  fontWeight: '600' }],
      },
      letterSpacing: { label: '0.1em' },
      borderRadius: {
        sm:   '0.25rem',
        md:   '0.5rem',
        lg:   '0.75rem',
        xl:   '1rem',
        '2xl':'1.5rem',
        '3xl':'2rem',
      },
      backgroundImage: {
        'gradient-brand':  'linear-gradient(135deg, #5b21b6 0%, #7c3aed 100%)',
        'gradient-rose':   'linear-gradient(135deg, #be123c 0%, #e11d48 100%)',
        'gradient-gold':   'linear-gradient(135deg, #d97706 0%, #f59e0b 100%)',
        'gradient-hero':   'linear-gradient(135deg, #1e1035 0%, #2e1065 50%, #4c1d95 100%)',
        /* backward compat names */
        'gradient-maroon': 'linear-gradient(135deg, #5b21b6 0%, #7c3aed 100%)',
        'gradient-cream':  'linear-gradient(180deg, #ffffff 0%, #fdfcff 100%)',
      },
      boxShadow: {
        warm:         '0 4px 16px -4px rgba(109, 40, 217, 0.07)',
        'warm-lg':    '0 12px 32px -8px rgba(109, 40, 217, 0.12)',
        'warm-xl':    '0 24px 60px -12px rgba(109, 40, 217, 0.16)',
        gold:         '0 8px 24px -6px rgba(217, 119, 6, 0.35)',
        maroon:       '0 8px 24px -6px rgba(109, 40, 217, 0.30)',
        card:         '0 2px 16px -4px rgba(109, 40, 217, 0.06)',
        'card-hover': '0 16px 40px -10px rgba(109, 40, 217, 0.14)',
      },
      keyframes: {
        'accordion-down': { from: { height: '0' }, to: { height: 'var(--radix-accordion-content-height)' } },
        'accordion-up':   { from: { height: 'var(--radix-accordion-content-height)' }, to: { height: '0' } },
        'fade-in':        { from: { opacity: '0' }, to: { opacity: '1' } },
        'fade-up':        { from: { opacity: '0', transform: 'translateY(20px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        shimmer:          { '0%': { backgroundPosition: '-200% 0' }, '100%': { backgroundPosition: '200% 0' } },
        float:            { '0%, 100%': { transform: 'translateY(0)' }, '50%': { transform: 'translateY(-10px)' } },
        'float-slow':     { '0%, 100%': { transform: 'translateY(0) rotate(0deg)' }, '50%': { transform: 'translateY(-16px) rotate(2deg)' } },
        'spin-slow':      { from: { transform: 'rotate(0deg)' }, to: { transform: 'rotate(360deg)' } },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up':   'accordion-up 0.2s ease-out',
        'fade-in':        'fade-in 0.4s ease-out',
        'fade-up':        'fade-up 0.5s ease-out',
        shimmer:          'shimmer 2s linear infinite',
        float:            'float 4s ease-in-out infinite',
        'float-slow':     'float-slow 7s ease-in-out infinite',
        'spin-slow':      'spin-slow 30s linear infinite',
      },
    },
  },
  plugins: [animate],
};

export default config;
