export enum ErrorCode {
  // Generic
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  CONFLICT = 'CONFLICT',
  BAD_REQUEST = 'BAD_REQUEST',
  RATE_LIMITED = 'RATE_LIMITED',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
  GONE = 'GONE',

  // Auth
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID = 'AUTH_TOKEN_INVALID',
  AUTH_TOKEN_MISSING = 'AUTH_TOKEN_MISSING',
  AUTH_REFRESH_TOKEN_INVALID = 'AUTH_REFRESH_TOKEN_INVALID',
  AUTH_REFRESH_TOKEN_EXPIRED = 'AUTH_REFRESH_TOKEN_EXPIRED',
  AUTH_OTP_INVALID = 'AUTH_OTP_INVALID',
  AUTH_OTP_EXPIRED = 'AUTH_OTP_EXPIRED',
  AUTH_OTP_MAX_ATTEMPTS = 'AUTH_OTP_MAX_ATTEMPTS',
  AUTH_OTP_RESEND_COOLDOWN = 'AUTH_OTP_RESEND_COOLDOWN',
  AUTH_ACCOUNT_LOCKED = 'AUTH_ACCOUNT_LOCKED',
  AUTH_ACCOUNT_SUSPENDED = 'AUTH_ACCOUNT_SUSPENDED',
  AUTH_ACCOUNT_DELETED = 'AUTH_ACCOUNT_DELETED',
  AUTH_ACCOUNT_NOT_VERIFIED = 'AUTH_ACCOUNT_NOT_VERIFIED',
  AUTH_2FA_REQUIRED = 'AUTH_2FA_REQUIRED',
  AUTH_2FA_INVALID = 'AUTH_2FA_INVALID',
  AUTH_SESSION_NOT_FOUND = 'AUTH_SESSION_NOT_FOUND',
  AUTH_SUSPICIOUS_LOGIN = 'AUTH_SUSPICIOUS_LOGIN',
  AUTH_DEVICE_NOT_FOUND = 'AUTH_DEVICE_NOT_FOUND',
  AUTH_MAX_SESSIONS = 'AUTH_MAX_SESSIONS',
  AUTH_GOOGLE_FAILED = 'AUTH_GOOGLE_FAILED',

  // Users / Profiles
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  USER_PHONE_TAKEN = 'USER_PHONE_TAKEN',
  USER_EMAIL_TAKEN = 'USER_EMAIL_TAKEN',
  USER_PROFILE_INCOMPLETE = 'USER_PROFILE_INCOMPLETE',
  USER_BLOCKED = 'USER_BLOCKED',
  USER_REPORTED = 'USER_REPORTED',

  // Subscription / Plan
  SUBSCRIPTION_REQUIRED = 'SUBSCRIPTION_REQUIRED',
  SUBSCRIPTION_EXPIRED = 'SUBSCRIPTION_EXPIRED',
  SUBSCRIPTION_NOT_FOUND = 'SUBSCRIPTION_NOT_FOUND',
  PLAN_UPGRADE_REQUIRED = 'PLAN_UPGRADE_REQUIRED',

  // Permissions
  PERMISSION_DENIED = 'PERMISSION_DENIED',
  FEATURE_DISABLED = 'FEATURE_DISABLED',
  FEATURE_FLAG_DISABLED = 'FEATURE_FLAG_DISABLED',

  // Payments
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  PAYMENT_NOT_FOUND = 'PAYMENT_NOT_FOUND',
  PAYMENT_ALREADY_PROCESSED = 'PAYMENT_ALREADY_PROCESSED',
  PAYMENT_VERIFICATION_FAILED = 'PAYMENT_VERIFICATION_FAILED',
  COUPON_INVALID = 'COUPON_INVALID',
  COUPON_EXPIRED = 'COUPON_EXPIRED',
  COUPON_USAGE_LIMIT = 'COUPON_USAGE_LIMIT',
  WALLET_INSUFFICIENT = 'WALLET_INSUFFICIENT',

  // Chat
  CHAT_NOT_FOUND = 'CHAT_NOT_FOUND',
  CHAT_ACCESS_DENIED = 'CHAT_ACCESS_DENIED',
  MESSAGE_NOT_FOUND = 'MESSAGE_NOT_FOUND',

  // Interests
  INTEREST_NOT_FOUND = 'INTEREST_NOT_FOUND',
  INTEREST_ALREADY_SENT = 'INTEREST_ALREADY_SENT',
  INTEREST_LIMIT_REACHED = 'INTEREST_LIMIT_REACHED',
  INTEREST_SELF_NOT_ALLOWED = 'INTEREST_SELF_NOT_ALLOWED',

  // Upload
  FILE_TOO_LARGE = 'FILE_TOO_LARGE',
  FILE_TYPE_NOT_ALLOWED = 'FILE_TYPE_NOT_ALLOWED',
  FILE_UPLOAD_FAILED = 'FILE_UPLOAD_FAILED',
  FILE_NOT_FOUND = 'FILE_NOT_FOUND',

  // Verification
  VERIFICATION_ALREADY_SUBMITTED = 'VERIFICATION_ALREADY_SUBMITTED',
  VERIFICATION_PENDING = 'VERIFICATION_PENDING',
  VERIFICATION_REJECTED = 'VERIFICATION_REJECTED',

  // Calls
  CALL_NOT_FOUND = 'CALL_NOT_FOUND',
  CALL_TOKEN_FAILED = 'CALL_TOKEN_FAILED',
  CALL_ACCESS_DENIED = 'CALL_ACCESS_DENIED',

  // Notifications
  NOTIFICATION_NOT_FOUND = 'NOTIFICATION_NOT_FOUND',

  // Support
  TICKET_NOT_FOUND = 'TICKET_NOT_FOUND',

  // Data
  EXPORT_FAILED = 'EXPORT_FAILED',
}
