/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SuccessStoriesRouteImport } from './routes/success-stories'
import { Route as RelationshipAdviceRouteImport } from './routes/relationship-advice'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as BlogsRouteImport } from './routes/blogs'
import { Route as AstrologyArticlesRouteImport } from './routes/astrology-articles'
import { Route as AiMatchingRouteImport } from './routes/ai-matching'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WalletIndexRouteImport } from './routes/wallet/index'
import { Route as VerificationIndexRouteImport } from './routes/verification/index'
import { Route as SupportIndexRouteImport } from './routes/support/index'
import { Route as SubscriptionsIndexRouteImport } from './routes/subscriptions/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SearchIndexRouteImport } from './routes/search/index'
import { Route as RelationshipAdviceIndexRouteImport } from './routes/relationship-advice/index'
import { Route as ReferralsIndexRouteImport } from './routes/referrals/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as NotificationsIndexRouteImport } from './routes/notifications/index'
import { Route as MeetingsIndexRouteImport } from './routes/meetings/index'
import { Route as MatchesIndexRouteImport } from './routes/matches/index'
import { Route as MarketplaceIndexRouteImport } from './routes/marketplace/index'
import { Route as InterestsIndexRouteImport } from './routes/interests/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as ChatIndexRouteImport } from './routes/chat/index'
import { Route as CallsIndexRouteImport } from './routes/calls/index'
import { Route as BlogsIndexRouteImport } from './routes/blogs/index'
import { Route as AstrologyIndexRouteImport } from './routes/astrology/index'
import { Route as ActivityIndexRouteImport } from './routes/activity/index'
import { Route as RelationshipAdviceSlugRouteImport } from './routes/relationship-advice/$slug'
import { Route as ProviderSlotsRouteImport } from './routes/provider/slots'
import { Route as ProviderRegisterRouteImport } from './routes/provider/register'
import { Route as ProviderLoginRouteImport } from './routes/provider/login'
import { Route as ProviderDashboardRouteImport } from './routes/provider/dashboard'
import { Route as ProviderBookingsRouteImport } from './routes/provider/bookings'
import { Route as ProfileEditRouteImport } from './routes/profile/edit'
import { Route as ProfileUserIdRouteImport } from './routes/profile/$userId'
import { Route as MatchesAiRouteImport } from './routes/matches/ai'
import { Route as MarketplaceCategoryRouteImport } from './routes/marketplace/$category'
import { Route as CallsActiveRouteImport } from './routes/calls/active'
import { Route as BlogsSlugRouteImport } from './routes/blogs/$slug'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as MarketplaceProviderProviderIdRouteImport } from './routes/marketplace/provider.$providerId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessStoriesRoute = SuccessStoriesRouteImport.update({
  id: '/success-stories',
  path: '/success-stories',
  getParentRoute: () => rootRouteImport,
} as any)
const RelationshipAdviceRoute = RelationshipAdviceRouteImport.update({
  id: '/relationship-advice',
  path: '/relationship-advice',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsRoute = BlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const AstrologyArticlesRoute = AstrologyArticlesRouteImport.update({
  id: '/astrology-articles',
  path: '/astrology-articles',
  getParentRoute: () => rootRouteImport,
} as any)
const AiMatchingRoute = AiMatchingRouteImport.update({
  id: '/ai-matching',
  path: '/ai-matching',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletIndexRoute = WalletIndexRouteImport.update({
  id: '/wallet/',
  path: '/wallet/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificationIndexRoute = VerificationIndexRouteImport.update({
  id: '/verification/',
  path: '/verification/',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportIndexRoute = SupportIndexRouteImport.update({
  id: '/support/',
  path: '/support/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionsIndexRoute = SubscriptionsIndexRouteImport.update({
  id: '/subscriptions/',
  path: '/subscriptions/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchIndexRoute = SearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => rootRouteImport,
} as any)
const RelationshipAdviceIndexRoute = RelationshipAdviceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RelationshipAdviceRoute,
} as any)
const ReferralsIndexRoute = ReferralsIndexRouteImport.update({
  id: '/referrals/',
  path: '/referrals/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsIndexRoute = NotificationsIndexRouteImport.update({
  id: '/notifications/',
  path: '/notifications/',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingsIndexRoute = MeetingsIndexRouteImport.update({
  id: '/meetings/',
  path: '/meetings/',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesIndexRoute = MatchesIndexRouteImport.update({
  id: '/matches/',
  path: '/matches/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceIndexRoute = MarketplaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketplaceRoute,
} as any)
const InterestsIndexRoute = InterestsIndexRouteImport.update({
  id: '/interests/',
  path: '/interests/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const CallsIndexRoute = CallsIndexRouteImport.update({
  id: '/calls/',
  path: '/calls/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsIndexRoute = BlogsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogsRoute,
} as any)
const AstrologyIndexRoute = AstrologyIndexRouteImport.update({
  id: '/astrology/',
  path: '/astrology/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityIndexRoute = ActivityIndexRouteImport.update({
  id: '/activity/',
  path: '/activity/',
  getParentRoute: () => rootRouteImport,
} as any)
const RelationshipAdviceSlugRoute = RelationshipAdviceSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => RelationshipAdviceRoute,
} as any)
const ProviderSlotsRoute = ProviderSlotsRouteImport.update({
  id: '/provider/slots',
  path: '/provider/slots',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderRegisterRoute = ProviderRegisterRouteImport.update({
  id: '/provider/register',
  path: '/provider/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderLoginRoute = ProviderLoginRouteImport.update({
  id: '/provider/login',
  path: '/provider/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderDashboardRoute = ProviderDashboardRouteImport.update({
  id: '/provider/dashboard',
  path: '/provider/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderBookingsRoute = ProviderBookingsRouteImport.update({
  id: '/provider/bookings',
  path: '/provider/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileEditRoute = ProfileEditRouteImport.update({
  id: '/profile/edit',
  path: '/profile/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUserIdRoute = ProfileUserIdRouteImport.update({
  id: '/profile/$userId',
  path: '/profile/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesAiRoute = MatchesAiRouteImport.update({
  id: '/matches/ai',
  path: '/matches/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceCategoryRoute = MarketplaceCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => MarketplaceRoute,
} as any)
const CallsActiveRoute = CallsActiveRouteImport.update({
  id: '/calls/active',
  path: '/calls/active',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsSlugRoute = BlogsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogsRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceProviderProviderIdRoute =
  MarketplaceProviderProviderIdRouteImport.update({
    id: '/provider/$providerId',
    path: '/provider/$providerId',
    getParentRoute: () => MarketplaceRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-matching': typeof AiMatchingRoute
  '/astrology-articles': typeof AstrologyArticlesRoute
  '/blogs': typeof BlogsRouteWithChildren
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/relationship-advice': typeof RelationshipAdviceRouteWithChildren
  '/success-stories': typeof SuccessStoriesRoute
  '/terms': typeof TermsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/calls/active': typeof CallsActiveRoute
  '/marketplace/$category': typeof MarketplaceCategoryRoute
  '/matches/ai': typeof MatchesAiRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/profile/edit': typeof ProfileEditRoute
  '/provider/bookings': typeof ProviderBookingsRoute
  '/provider/dashboard': typeof ProviderDashboardRoute
  '/provider/login': typeof ProviderLoginRoute
  '/provider/register': typeof ProviderRegisterRoute
  '/provider/slots': typeof ProviderSlotsRoute
  '/relationship-advice/$slug': typeof RelationshipAdviceSlugRoute
  '/activity/': typeof ActivityIndexRoute
  '/astrology/': typeof AstrologyIndexRoute
  '/blogs/': typeof BlogsIndexRoute
  '/calls/': typeof CallsIndexRoute
  '/chat/': typeof ChatIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/interests/': typeof InterestsIndexRoute
  '/marketplace/': typeof MarketplaceIndexRoute
  '/matches/': typeof MatchesIndexRoute
  '/meetings/': typeof MeetingsIndexRoute
  '/notifications/': typeof NotificationsIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/referrals/': typeof ReferralsIndexRoute
  '/relationship-advice/': typeof RelationshipAdviceIndexRoute
  '/search/': typeof SearchIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/subscriptions/': typeof SubscriptionsIndexRoute
  '/support/': typeof SupportIndexRoute
  '/verification/': typeof VerificationIndexRoute
  '/wallet/': typeof WalletIndexRoute
  '/marketplace/provider/$providerId': typeof MarketplaceProviderProviderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-matching': typeof AiMatchingRoute
  '/astrology-articles': typeof AstrologyArticlesRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/terms': typeof TermsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/calls/active': typeof CallsActiveRoute
  '/marketplace/$category': typeof MarketplaceCategoryRoute
  '/matches/ai': typeof MatchesAiRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/profile/edit': typeof ProfileEditRoute
  '/provider/bookings': typeof ProviderBookingsRoute
  '/provider/dashboard': typeof ProviderDashboardRoute
  '/provider/login': typeof ProviderLoginRoute
  '/provider/register': typeof ProviderRegisterRoute
  '/provider/slots': typeof ProviderSlotsRoute
  '/relationship-advice/$slug': typeof RelationshipAdviceSlugRoute
  '/activity': typeof ActivityIndexRoute
  '/astrology': typeof AstrologyIndexRoute
  '/blogs': typeof BlogsIndexRoute
  '/calls': typeof CallsIndexRoute
  '/chat': typeof ChatIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/interests': typeof InterestsIndexRoute
  '/marketplace': typeof MarketplaceIndexRoute
  '/matches': typeof MatchesIndexRoute
  '/meetings': typeof MeetingsIndexRoute
  '/notifications': typeof NotificationsIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/referrals': typeof ReferralsIndexRoute
  '/relationship-advice': typeof RelationshipAdviceIndexRoute
  '/search': typeof SearchIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/subscriptions': typeof SubscriptionsIndexRoute
  '/support': typeof SupportIndexRoute
  '/verification': typeof VerificationIndexRoute
  '/wallet': typeof WalletIndexRoute
  '/marketplace/provider/$providerId': typeof MarketplaceProviderProviderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-matching': typeof AiMatchingRoute
  '/astrology-articles': typeof AstrologyArticlesRoute
  '/blogs': typeof BlogsRouteWithChildren
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/relationship-advice': typeof RelationshipAdviceRouteWithChildren
  '/success-stories': typeof SuccessStoriesRoute
  '/terms': typeof TermsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/calls/active': typeof CallsActiveRoute
  '/marketplace/$category': typeof MarketplaceCategoryRoute
  '/matches/ai': typeof MatchesAiRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/profile/edit': typeof ProfileEditRoute
  '/provider/bookings': typeof ProviderBookingsRoute
  '/provider/dashboard': typeof ProviderDashboardRoute
  '/provider/login': typeof ProviderLoginRoute
  '/provider/register': typeof ProviderRegisterRoute
  '/provider/slots': typeof ProviderSlotsRoute
  '/relationship-advice/$slug': typeof RelationshipAdviceSlugRoute
  '/activity/': typeof ActivityIndexRoute
  '/astrology/': typeof AstrologyIndexRoute
  '/blogs/': typeof BlogsIndexRoute
  '/calls/': typeof CallsIndexRoute
  '/chat/': typeof ChatIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/interests/': typeof InterestsIndexRoute
  '/marketplace/': typeof MarketplaceIndexRoute
  '/matches/': typeof MatchesIndexRoute
  '/meetings/': typeof MeetingsIndexRoute
  '/notifications/': typeof NotificationsIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/referrals/': typeof ReferralsIndexRoute
  '/relationship-advice/': typeof RelationshipAdviceIndexRoute
  '/search/': typeof SearchIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/subscriptions/': typeof SubscriptionsIndexRoute
  '/support/': typeof SupportIndexRoute
  '/verification/': typeof VerificationIndexRoute
  '/wallet/': typeof WalletIndexRoute
  '/marketplace/provider/$providerId': typeof MarketplaceProviderProviderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ai-matching'
    | '/astrology-articles'
    | '/blogs'
    | '/careers'
    | '/contact'
    | '/cookie-policy'
    | '/faq'
    | '/how-it-works'
    | '/marketplace'
    | '/pricing'
    | '/privacy-policy'
    | '/relationship-advice'
    | '/success-stories'
    | '/terms'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/blogs/$slug'
    | '/calls/active'
    | '/marketplace/$category'
    | '/matches/ai'
    | '/profile/$userId'
    | '/profile/edit'
    | '/provider/bookings'
    | '/provider/dashboard'
    | '/provider/login'
    | '/provider/register'
    | '/provider/slots'
    | '/relationship-advice/$slug'
    | '/activity/'
    | '/astrology/'
    | '/blogs/'
    | '/calls/'
    | '/chat/'
    | '/dashboard/'
    | '/interests/'
    | '/marketplace/'
    | '/matches/'
    | '/meetings/'
    | '/notifications/'
    | '/onboarding/'
    | '/referrals/'
    | '/relationship-advice/'
    | '/search/'
    | '/settings/'
    | '/subscriptions/'
    | '/support/'
    | '/verification/'
    | '/wallet/'
    | '/marketplace/provider/$providerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ai-matching'
    | '/astrology-articles'
    | '/careers'
    | '/contact'
    | '/cookie-policy'
    | '/faq'
    | '/how-it-works'
    | '/pricing'
    | '/privacy-policy'
    | '/success-stories'
    | '/terms'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/blogs/$slug'
    | '/calls/active'
    | '/marketplace/$category'
    | '/matches/ai'
    | '/profile/$userId'
    | '/profile/edit'
    | '/provider/bookings'
    | '/provider/dashboard'
    | '/provider/login'
    | '/provider/register'
    | '/provider/slots'
    | '/relationship-advice/$slug'
    | '/activity'
    | '/astrology'
    | '/blogs'
    | '/calls'
    | '/chat'
    | '/dashboard'
    | '/interests'
    | '/marketplace'
    | '/matches'
    | '/meetings'
    | '/notifications'
    | '/onboarding'
    | '/referrals'
    | '/relationship-advice'
    | '/search'
    | '/settings'
    | '/subscriptions'
    | '/support'
    | '/verification'
    | '/wallet'
    | '/marketplace/provider/$providerId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ai-matching'
    | '/astrology-articles'
    | '/blogs'
    | '/careers'
    | '/contact'
    | '/cookie-policy'
    | '/faq'
    | '/how-it-works'
    | '/marketplace'
    | '/pricing'
    | '/privacy-policy'
    | '/relationship-advice'
    | '/success-stories'
    | '/terms'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/blogs/$slug'
    | '/calls/active'
    | '/marketplace/$category'
    | '/matches/ai'
    | '/profile/$userId'
    | '/profile/edit'
    | '/provider/bookings'
    | '/provider/dashboard'
    | '/provider/login'
    | '/provider/register'
    | '/provider/slots'
    | '/relationship-advice/$slug'
    | '/activity/'
    | '/astrology/'
    | '/blogs/'
    | '/calls/'
    | '/chat/'
    | '/dashboard/'
    | '/interests/'
    | '/marketplace/'
    | '/matches/'
    | '/meetings/'
    | '/notifications/'
    | '/onboarding/'
    | '/referrals/'
    | '/relationship-advice/'
    | '/search/'
    | '/settings/'
    | '/subscriptions/'
    | '/support/'
    | '/verification/'
    | '/wallet/'
    | '/marketplace/provider/$providerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AiMatchingRoute: typeof AiMatchingRoute
  AstrologyArticlesRoute: typeof AstrologyArticlesRoute
  BlogsRoute: typeof BlogsRouteWithChildren
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  FaqRoute: typeof FaqRoute
  HowItWorksRoute: typeof HowItWorksRoute
  MarketplaceRoute: typeof MarketplaceRouteWithChildren
  PricingRoute: typeof PricingRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RelationshipAdviceRoute: typeof RelationshipAdviceRouteWithChildren
  SuccessStoriesRoute: typeof SuccessStoriesRoute
  TermsRoute: typeof TermsRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  CallsActiveRoute: typeof CallsActiveRoute
  MatchesAiRoute: typeof MatchesAiRoute
  ProfileUserIdRoute: typeof ProfileUserIdRoute
  ProfileEditRoute: typeof ProfileEditRoute
  ProviderBookingsRoute: typeof ProviderBookingsRoute
  ProviderDashboardRoute: typeof ProviderDashboardRoute
  ProviderLoginRoute: typeof ProviderLoginRoute
  ProviderRegisterRoute: typeof ProviderRegisterRoute
  ProviderSlotsRoute: typeof ProviderSlotsRoute
  ActivityIndexRoute: typeof ActivityIndexRoute
  AstrologyIndexRoute: typeof AstrologyIndexRoute
  CallsIndexRoute: typeof CallsIndexRoute
  ChatIndexRoute: typeof ChatIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  InterestsIndexRoute: typeof InterestsIndexRoute
  MatchesIndexRoute: typeof MatchesIndexRoute
  MeetingsIndexRoute: typeof MeetingsIndexRoute
  NotificationsIndexRoute: typeof NotificationsIndexRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
  ReferralsIndexRoute: typeof ReferralsIndexRoute
  SearchIndexRoute: typeof SearchIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  SubscriptionsIndexRoute: typeof SubscriptionsIndexRoute
  SupportIndexRoute: typeof SupportIndexRoute
  VerificationIndexRoute: typeof VerificationIndexRoute
  WalletIndexRoute: typeof WalletIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success-stories': {
      id: '/success-stories'
      path: '/success-stories'
      fullPath: '/success-stories'
      preLoaderRoute: typeof SuccessStoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relationship-advice': {
      id: '/relationship-advice'
      path: '/relationship-advice'
      fullPath: '/relationship-advice'
      preLoaderRoute: typeof RelationshipAdviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs': {
      id: '/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof BlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/astrology-articles': {
      id: '/astrology-articles'
      path: '/astrology-articles'
      fullPath: '/astrology-articles'
      preLoaderRoute: typeof AstrologyArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-matching': {
      id: '/ai-matching'
      path: '/ai-matching'
      fullPath: '/ai-matching'
      preLoaderRoute: typeof AiMatchingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet/': {
      id: '/wallet/'
      path: '/wallet'
      fullPath: '/wallet/'
      preLoaderRoute: typeof WalletIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verification/': {
      id: '/verification/'
      path: '/verification'
      fullPath: '/verification/'
      preLoaderRoute: typeof VerificationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support/': {
      id: '/support/'
      path: '/support'
      fullPath: '/support/'
      preLoaderRoute: typeof SupportIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscriptions/': {
      id: '/subscriptions/'
      path: '/subscriptions'
      fullPath: '/subscriptions/'
      preLoaderRoute: typeof SubscriptionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search/': {
      id: '/search/'
      path: '/search'
      fullPath: '/search/'
      preLoaderRoute: typeof SearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relationship-advice/': {
      id: '/relationship-advice/'
      path: '/'
      fullPath: '/relationship-advice/'
      preLoaderRoute: typeof RelationshipAdviceIndexRouteImport
      parentRoute: typeof RelationshipAdviceRoute
    }
    '/referrals/': {
      id: '/referrals/'
      path: '/referrals'
      fullPath: '/referrals/'
      preLoaderRoute: typeof ReferralsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications/': {
      id: '/notifications/'
      path: '/notifications'
      fullPath: '/notifications/'
      preLoaderRoute: typeof NotificationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetings/': {
      id: '/meetings/'
      path: '/meetings'
      fullPath: '/meetings/'
      preLoaderRoute: typeof MeetingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/': {
      id: '/matches/'
      path: '/matches'
      fullPath: '/matches/'
      preLoaderRoute: typeof MatchesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/': {
      id: '/marketplace/'
      path: '/'
      fullPath: '/marketplace/'
      preLoaderRoute: typeof MarketplaceIndexRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/interests/': {
      id: '/interests/'
      path: '/interests'
      fullPath: '/interests/'
      preLoaderRoute: typeof InterestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/': {
      id: '/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calls/': {
      id: '/calls/'
      path: '/calls'
      fullPath: '/calls/'
      preLoaderRoute: typeof CallsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/': {
      id: '/blogs/'
      path: '/'
      fullPath: '/blogs/'
      preLoaderRoute: typeof BlogsIndexRouteImport
      parentRoute: typeof BlogsRoute
    }
    '/astrology/': {
      id: '/astrology/'
      path: '/astrology'
      fullPath: '/astrology/'
      preLoaderRoute: typeof AstrologyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity/': {
      id: '/activity/'
      path: '/activity'
      fullPath: '/activity/'
      preLoaderRoute: typeof ActivityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relationship-advice/$slug': {
      id: '/relationship-advice/$slug'
      path: '/$slug'
      fullPath: '/relationship-advice/$slug'
      preLoaderRoute: typeof RelationshipAdviceSlugRouteImport
      parentRoute: typeof RelationshipAdviceRoute
    }
    '/provider/slots': {
      id: '/provider/slots'
      path: '/provider/slots'
      fullPath: '/provider/slots'
      preLoaderRoute: typeof ProviderSlotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider/register': {
      id: '/provider/register'
      path: '/provider/register'
      fullPath: '/provider/register'
      preLoaderRoute: typeof ProviderRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider/login': {
      id: '/provider/login'
      path: '/provider/login'
      fullPath: '/provider/login'
      preLoaderRoute: typeof ProviderLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider/dashboard': {
      id: '/provider/dashboard'
      path: '/provider/dashboard'
      fullPath: '/provider/dashboard'
      preLoaderRoute: typeof ProviderDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider/bookings': {
      id: '/provider/bookings'
      path: '/provider/bookings'
      fullPath: '/provider/bookings'
      preLoaderRoute: typeof ProviderBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/edit': {
      id: '/profile/edit'
      path: '/profile/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof ProfileEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$userId': {
      id: '/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof ProfileUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/ai': {
      id: '/matches/ai'
      path: '/matches/ai'
      fullPath: '/matches/ai'
      preLoaderRoute: typeof MatchesAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/$category': {
      id: '/marketplace/$category'
      path: '/$category'
      fullPath: '/marketplace/$category'
      preLoaderRoute: typeof MarketplaceCategoryRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/calls/active': {
      id: '/calls/active'
      path: '/calls/active'
      fullPath: '/calls/active'
      preLoaderRoute: typeof CallsActiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/$slug': {
      id: '/blogs/$slug'
      path: '/$slug'
      fullPath: '/blogs/$slug'
      preLoaderRoute: typeof BlogsSlugRouteImport
      parentRoute: typeof BlogsRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/provider/$providerId': {
      id: '/marketplace/provider/$providerId'
      path: '/provider/$providerId'
      fullPath: '/marketplace/provider/$providerId'
      preLoaderRoute: typeof MarketplaceProviderProviderIdRouteImport
      parentRoute: typeof MarketplaceRoute
    }
  }
}

interface BlogsRouteChildren {
  BlogsSlugRoute: typeof BlogsSlugRoute
  BlogsIndexRoute: typeof BlogsIndexRoute
}

const BlogsRouteChildren: BlogsRouteChildren = {
  BlogsSlugRoute: BlogsSlugRoute,
  BlogsIndexRoute: BlogsIndexRoute,
}

const BlogsRouteWithChildren = BlogsRoute._addFileChildren(BlogsRouteChildren)

interface MarketplaceRouteChildren {
  MarketplaceCategoryRoute: typeof MarketplaceCategoryRoute
  MarketplaceIndexRoute: typeof MarketplaceIndexRoute
  MarketplaceProviderProviderIdRoute: typeof MarketplaceProviderProviderIdRoute
}

const MarketplaceRouteChildren: MarketplaceRouteChildren = {
  MarketplaceCategoryRoute: MarketplaceCategoryRoute,
  MarketplaceIndexRoute: MarketplaceIndexRoute,
  MarketplaceProviderProviderIdRoute: MarketplaceProviderProviderIdRoute,
}

const MarketplaceRouteWithChildren = MarketplaceRoute._addFileChildren(
  MarketplaceRouteChildren,
)

interface RelationshipAdviceRouteChildren {
  RelationshipAdviceSlugRoute: typeof RelationshipAdviceSlugRoute
  RelationshipAdviceIndexRoute: typeof RelationshipAdviceIndexRoute
}

const RelationshipAdviceRouteChildren: RelationshipAdviceRouteChildren = {
  RelationshipAdviceSlugRoute: RelationshipAdviceSlugRoute,
  RelationshipAdviceIndexRoute: RelationshipAdviceIndexRoute,
}

const RelationshipAdviceRouteWithChildren =
  RelationshipAdviceRoute._addFileChildren(RelationshipAdviceRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AiMatchingRoute: AiMatchingRoute,
  AstrologyArticlesRoute: AstrologyArticlesRoute,
  BlogsRoute: BlogsRouteWithChildren,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  FaqRoute: FaqRoute,
  HowItWorksRoute: HowItWorksRoute,
  MarketplaceRoute: MarketplaceRouteWithChildren,
  PricingRoute: PricingRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RelationshipAdviceRoute: RelationshipAdviceRouteWithChildren,
  SuccessStoriesRoute: SuccessStoriesRoute,
  TermsRoute: TermsRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  CallsActiveRoute: CallsActiveRoute,
  MatchesAiRoute: MatchesAiRoute,
  ProfileUserIdRoute: ProfileUserIdRoute,
  ProfileEditRoute: ProfileEditRoute,
  ProviderBookingsRoute: ProviderBookingsRoute,
  ProviderDashboardRoute: ProviderDashboardRoute,
  ProviderLoginRoute: ProviderLoginRoute,
  ProviderRegisterRoute: ProviderRegisterRoute,
  ProviderSlotsRoute: ProviderSlotsRoute,
  ActivityIndexRoute: ActivityIndexRoute,
  AstrologyIndexRoute: AstrologyIndexRoute,
  CallsIndexRoute: CallsIndexRoute,
  ChatIndexRoute: ChatIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  InterestsIndexRoute: InterestsIndexRoute,
  MatchesIndexRoute: MatchesIndexRoute,
  MeetingsIndexRoute: MeetingsIndexRoute,
  NotificationsIndexRoute: NotificationsIndexRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
  ReferralsIndexRoute: ReferralsIndexRoute,
  SearchIndexRoute: SearchIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  SubscriptionsIndexRoute: SubscriptionsIndexRoute,
  SupportIndexRoute: SupportIndexRoute,
  VerificationIndexRoute: VerificationIndexRoute,
  WalletIndexRoute: WalletIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
