/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as VerificationRouteImport } from './routes/verification'
import { Route as SystemConfigRouteImport } from './routes/system-config'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SuccessStoriesRouteImport } from './routes/success-stories'
import { Route as SubscriptionsRouteImport } from './routes/subscriptions'
import { Route as StorageRouteImport } from './routes/storage'
import { Route as SeoRouteImport } from './routes/seo'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as SearchMgmtRouteImport } from './routes/search-mgmt'
import { Route as ReferralsRouteImport } from './routes/referrals'
import { Route as RecommendationAnalyticsRouteImport } from './routes/recommendation-analytics'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MonitoringRouteImport } from './routes/monitoring'
import { Route as ModerationRouteImport } from './routes/moderation'
import { Route as MeetingsRouteImport } from './routes/meetings'
import { Route as MatchmakingRouteImport } from './routes/matchmaking'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InterestsRouteImport } from './routes/interests'
import { Route as FraudRouteImport } from './routes/fraud'
import { Route as FeatureFlagsRouteImport } from './routes/feature-flags'
import { Route as FamilyRouteImport } from './routes/family'
import { Route as DataExportRouteImport } from './routes/data-export'
import { Route as CronRouteImport } from './routes/cron'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as CmsRouteImport } from './routes/cms'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CallsRouteImport } from './routes/calls'
import { Route as BackgroundVerificationRouteImport } from './routes/background-verification'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AnnouncementsRouteImport } from './routes/announcements'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AiRouteImport } from './routes/ai'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as AccountDeletionRouteImport } from './routes/account-deletion'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersIndexRouteImport } from './routes/users/index'
import { Route as UsersUserIdRouteImport } from './routes/users/$userId'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificationRoute = VerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemConfigRoute = SystemConfigRouteImport.update({
  id: '/system-config',
  path: '/system-config',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessStoriesRoute = SuccessStoriesRouteImport.update({
  id: '/success-stories',
  path: '/success-stories',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionsRoute = SubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const StorageRoute = StorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => rootRouteImport,
} as any)
const SeoRoute = SeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchMgmtRoute = SearchMgmtRouteImport.update({
  id: '/search-mgmt',
  path: '/search-mgmt',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralsRoute = ReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationAnalyticsRoute = RecommendationAnalyticsRouteImport.update({
  id: '/recommendation-analytics',
  path: '/recommendation-analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoringRoute = MonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const ModerationRoute = ModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingsRoute = MeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchmakingRoute = MatchmakingRouteImport.update({
  id: '/matchmaking',
  path: '/matchmaking',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InterestsRoute = InterestsRouteImport.update({
  id: '/interests',
  path: '/interests',
  getParentRoute: () => rootRouteImport,
} as any)
const FraudRoute = FraudRouteImport.update({
  id: '/fraud',
  path: '/fraud',
  getParentRoute: () => rootRouteImport,
} as any)
const FeatureFlagsRoute = FeatureFlagsRouteImport.update({
  id: '/feature-flags',
  path: '/feature-flags',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyRoute = FamilyRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => rootRouteImport,
} as any)
const DataExportRoute = DataExportRouteImport.update({
  id: '/data-export',
  path: '/data-export',
  getParentRoute: () => rootRouteImport,
} as any)
const CronRoute = CronRouteImport.update({
  id: '/cron',
  path: '/cron',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const CmsRoute = CmsRouteImport.update({
  id: '/cms',
  path: '/cms',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CallsRoute = CallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => rootRouteImport,
} as any)
const BackgroundVerificationRoute = BackgroundVerificationRouteImport.update({
  id: '/background-verification',
  path: '/background-verification',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsRoute = AnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountDeletionRoute = AccountDeletionRouteImport.update({
  id: '/account-deletion',
  path: '/account-deletion',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUserIdRoute = UsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account-deletion': typeof AccountDeletionRoute
  '/activity': typeof ActivityRoute
  '/ai': typeof AiRoute
  '/analytics': typeof AnalyticsRoute
  '/announcements': typeof AnnouncementsRoute
  '/audit': typeof AuditRoute
  '/background-verification': typeof BackgroundVerificationRoute
  '/calls': typeof CallsRoute
  '/chat': typeof ChatRoute
  '/cms': typeof CmsRoute
  '/crm': typeof CrmRoute
  '/cron': typeof CronRoute
  '/data-export': typeof DataExportRoute
  '/family': typeof FamilyRoute
  '/feature-flags': typeof FeatureFlagsRoute
  '/fraud': typeof FraudRoute
  '/interests': typeof InterestsRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/matchmaking': typeof MatchmakingRoute
  '/meetings': typeof MeetingsRoute
  '/moderation': typeof ModerationRoute
  '/monitoring': typeof MonitoringRoute
  '/notifications': typeof NotificationsRoute
  '/payments': typeof PaymentsRoute
  '/recommendation-analytics': typeof RecommendationAnalyticsRoute
  '/referrals': typeof ReferralsRoute
  '/search-mgmt': typeof SearchMgmtRoute
  '/security': typeof SecurityRoute
  '/seo': typeof SeoRoute
  '/storage': typeof StorageRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/support': typeof SupportRoute
  '/system-config': typeof SystemConfigRoute
  '/verification': typeof VerificationRoute
  '/wallet': typeof WalletRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/users/': typeof UsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account-deletion': typeof AccountDeletionRoute
  '/activity': typeof ActivityRoute
  '/ai': typeof AiRoute
  '/analytics': typeof AnalyticsRoute
  '/announcements': typeof AnnouncementsRoute
  '/audit': typeof AuditRoute
  '/background-verification': typeof BackgroundVerificationRoute
  '/calls': typeof CallsRoute
  '/chat': typeof ChatRoute
  '/cms': typeof CmsRoute
  '/crm': typeof CrmRoute
  '/cron': typeof CronRoute
  '/data-export': typeof DataExportRoute
  '/family': typeof FamilyRoute
  '/feature-flags': typeof FeatureFlagsRoute
  '/fraud': typeof FraudRoute
  '/interests': typeof InterestsRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/matchmaking': typeof MatchmakingRoute
  '/meetings': typeof MeetingsRoute
  '/moderation': typeof ModerationRoute
  '/monitoring': typeof MonitoringRoute
  '/notifications': typeof NotificationsRoute
  '/payments': typeof PaymentsRoute
  '/recommendation-analytics': typeof RecommendationAnalyticsRoute
  '/referrals': typeof ReferralsRoute
  '/search-mgmt': typeof SearchMgmtRoute
  '/security': typeof SecurityRoute
  '/seo': typeof SeoRoute
  '/storage': typeof StorageRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/support': typeof SupportRoute
  '/system-config': typeof SystemConfigRoute
  '/verification': typeof VerificationRoute
  '/wallet': typeof WalletRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/users': typeof UsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account-deletion': typeof AccountDeletionRoute
  '/activity': typeof ActivityRoute
  '/ai': typeof AiRoute
  '/analytics': typeof AnalyticsRoute
  '/announcements': typeof AnnouncementsRoute
  '/audit': typeof AuditRoute
  '/background-verification': typeof BackgroundVerificationRoute
  '/calls': typeof CallsRoute
  '/chat': typeof ChatRoute
  '/cms': typeof CmsRoute
  '/crm': typeof CrmRoute
  '/cron': typeof CronRoute
  '/data-export': typeof DataExportRoute
  '/family': typeof FamilyRoute
  '/feature-flags': typeof FeatureFlagsRoute
  '/fraud': typeof FraudRoute
  '/interests': typeof InterestsRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/matchmaking': typeof MatchmakingRoute
  '/meetings': typeof MeetingsRoute
  '/moderation': typeof ModerationRoute
  '/monitoring': typeof MonitoringRoute
  '/notifications': typeof NotificationsRoute
  '/payments': typeof PaymentsRoute
  '/recommendation-analytics': typeof RecommendationAnalyticsRoute
  '/referrals': typeof ReferralsRoute
  '/search-mgmt': typeof SearchMgmtRoute
  '/security': typeof SecurityRoute
  '/seo': typeof SeoRoute
  '/storage': typeof StorageRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/support': typeof SupportRoute
  '/system-config': typeof SystemConfigRoute
  '/verification': typeof VerificationRoute
  '/wallet': typeof WalletRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/users/': typeof UsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account-deletion'
    | '/activity'
    | '/ai'
    | '/analytics'
    | '/announcements'
    | '/audit'
    | '/background-verification'
    | '/calls'
    | '/chat'
    | '/cms'
    | '/crm'
    | '/cron'
    | '/data-export'
    | '/family'
    | '/feature-flags'
    | '/fraud'
    | '/interests'
    | '/login'
    | '/marketplace'
    | '/matchmaking'
    | '/meetings'
    | '/moderation'
    | '/monitoring'
    | '/notifications'
    | '/payments'
    | '/recommendation-analytics'
    | '/referrals'
    | '/search-mgmt'
    | '/security'
    | '/seo'
    | '/storage'
    | '/subscriptions'
    | '/success-stories'
    | '/support'
    | '/system-config'
    | '/verification'
    | '/wallet'
    | '/users/$userId'
    | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account-deletion'
    | '/activity'
    | '/ai'
    | '/analytics'
    | '/announcements'
    | '/audit'
    | '/background-verification'
    | '/calls'
    | '/chat'
    | '/cms'
    | '/crm'
    | '/cron'
    | '/data-export'
    | '/family'
    | '/feature-flags'
    | '/fraud'
    | '/interests'
    | '/login'
    | '/marketplace'
    | '/matchmaking'
    | '/meetings'
    | '/moderation'
    | '/monitoring'
    | '/notifications'
    | '/payments'
    | '/recommendation-analytics'
    | '/referrals'
    | '/search-mgmt'
    | '/security'
    | '/seo'
    | '/storage'
    | '/subscriptions'
    | '/success-stories'
    | '/support'
    | '/system-config'
    | '/verification'
    | '/wallet'
    | '/users/$userId'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/account-deletion'
    | '/activity'
    | '/ai'
    | '/analytics'
    | '/announcements'
    | '/audit'
    | '/background-verification'
    | '/calls'
    | '/chat'
    | '/cms'
    | '/crm'
    | '/cron'
    | '/data-export'
    | '/family'
    | '/feature-flags'
    | '/fraud'
    | '/interests'
    | '/login'
    | '/marketplace'
    | '/matchmaking'
    | '/meetings'
    | '/moderation'
    | '/monitoring'
    | '/notifications'
    | '/payments'
    | '/recommendation-analytics'
    | '/referrals'
    | '/search-mgmt'
    | '/security'
    | '/seo'
    | '/storage'
    | '/subscriptions'
    | '/success-stories'
    | '/support'
    | '/system-config'
    | '/verification'
    | '/wallet'
    | '/users/$userId'
    | '/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountDeletionRoute: typeof AccountDeletionRoute
  ActivityRoute: typeof ActivityRoute
  AiRoute: typeof AiRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AnnouncementsRoute: typeof AnnouncementsRoute
  AuditRoute: typeof AuditRoute
  BackgroundVerificationRoute: typeof BackgroundVerificationRoute
  CallsRoute: typeof CallsRoute
  ChatRoute: typeof ChatRoute
  CmsRoute: typeof CmsRoute
  CrmRoute: typeof CrmRoute
  CronRoute: typeof CronRoute
  DataExportRoute: typeof DataExportRoute
  FamilyRoute: typeof FamilyRoute
  FeatureFlagsRoute: typeof FeatureFlagsRoute
  FraudRoute: typeof FraudRoute
  InterestsRoute: typeof InterestsRoute
  LoginRoute: typeof LoginRoute
  MarketplaceRoute: typeof MarketplaceRoute
  MatchmakingRoute: typeof MatchmakingRoute
  MeetingsRoute: typeof MeetingsRoute
  ModerationRoute: typeof ModerationRoute
  MonitoringRoute: typeof MonitoringRoute
  NotificationsRoute: typeof NotificationsRoute
  PaymentsRoute: typeof PaymentsRoute
  RecommendationAnalyticsRoute: typeof RecommendationAnalyticsRoute
  ReferralsRoute: typeof ReferralsRoute
  SearchMgmtRoute: typeof SearchMgmtRoute
  SecurityRoute: typeof SecurityRoute
  SeoRoute: typeof SeoRoute
  StorageRoute: typeof StorageRoute
  SubscriptionsRoute: typeof SubscriptionsRoute
  SuccessStoriesRoute: typeof SuccessStoriesRoute
  SupportRoute: typeof SupportRoute
  SystemConfigRoute: typeof SystemConfigRoute
  VerificationRoute: typeof VerificationRoute
  WalletRoute: typeof WalletRoute
  UsersUserIdRoute: typeof UsersUserIdRoute
  UsersIndexRoute: typeof UsersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verification': {
      id: '/verification'
      path: '/verification'
      fullPath: '/verification'
      preLoaderRoute: typeof VerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system-config': {
      id: '/system-config'
      path: '/system-config'
      fullPath: '/system-config'
      preLoaderRoute: typeof SystemConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success-stories': {
      id: '/success-stories'
      path: '/success-stories'
      fullPath: '/success-stories'
      preLoaderRoute: typeof SuccessStoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscriptions': {
      id: '/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof SubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storage': {
      id: '/storage'
      path: '/storage'
      fullPath: '/storage'
      preLoaderRoute: typeof StorageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seo': {
      id: '/seo'
      path: '/seo'
      fullPath: '/seo'
      preLoaderRoute: typeof SeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search-mgmt': {
      id: '/search-mgmt'
      path: '/search-mgmt'
      fullPath: '/search-mgmt'
      preLoaderRoute: typeof SearchMgmtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referrals': {
      id: '/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof ReferralsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendation-analytics': {
      id: '/recommendation-analytics'
      path: '/recommendation-analytics'
      fullPath: '/recommendation-analytics'
      preLoaderRoute: typeof RecommendationAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoring': {
      id: '/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof MonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moderation': {
      id: '/moderation'
      path: '/moderation'
      fullPath: '/moderation'
      preLoaderRoute: typeof ModerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetings': {
      id: '/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof MeetingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matchmaking': {
      id: '/matchmaking'
      path: '/matchmaking'
      fullPath: '/matchmaking'
      preLoaderRoute: typeof MatchmakingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interests': {
      id: '/interests'
      path: '/interests'
      fullPath: '/interests'
      preLoaderRoute: typeof InterestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fraud': {
      id: '/fraud'
      path: '/fraud'
      fullPath: '/fraud'
      preLoaderRoute: typeof FraudRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feature-flags': {
      id: '/feature-flags'
      path: '/feature-flags'
      fullPath: '/feature-flags'
      preLoaderRoute: typeof FeatureFlagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family': {
      id: '/family'
      path: '/family'
      fullPath: '/family'
      preLoaderRoute: typeof FamilyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-export': {
      id: '/data-export'
      path: '/data-export'
      fullPath: '/data-export'
      preLoaderRoute: typeof DataExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cron': {
      id: '/cron'
      path: '/cron'
      fullPath: '/cron'
      preLoaderRoute: typeof CronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cms': {
      id: '/cms'
      path: '/cms'
      fullPath: '/cms'
      preLoaderRoute: typeof CmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calls': {
      id: '/calls'
      path: '/calls'
      fullPath: '/calls'
      preLoaderRoute: typeof CallsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/background-verification': {
      id: '/background-verification'
      path: '/background-verification'
      fullPath: '/background-verification'
      preLoaderRoute: typeof BackgroundVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements': {
      id: '/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account-deletion': {
      id: '/account-deletion'
      path: '/account-deletion'
      fullPath: '/account-deletion'
      preLoaderRoute: typeof AccountDeletionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$userId': {
      id: '/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof UsersUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountDeletionRoute: AccountDeletionRoute,
  ActivityRoute: ActivityRoute,
  AiRoute: AiRoute,
  AnalyticsRoute: AnalyticsRoute,
  AnnouncementsRoute: AnnouncementsRoute,
  AuditRoute: AuditRoute,
  BackgroundVerificationRoute: BackgroundVerificationRoute,
  CallsRoute: CallsRoute,
  ChatRoute: ChatRoute,
  CmsRoute: CmsRoute,
  CrmRoute: CrmRoute,
  CronRoute: CronRoute,
  DataExportRoute: DataExportRoute,
  FamilyRoute: FamilyRoute,
  FeatureFlagsRoute: FeatureFlagsRoute,
  FraudRoute: FraudRoute,
  InterestsRoute: InterestsRoute,
  LoginRoute: LoginRoute,
  MarketplaceRoute: MarketplaceRoute,
  MatchmakingRoute: MatchmakingRoute,
  MeetingsRoute: MeetingsRoute,
  ModerationRoute: ModerationRoute,
  MonitoringRoute: MonitoringRoute,
  NotificationsRoute: NotificationsRoute,
  PaymentsRoute: PaymentsRoute,
  RecommendationAnalyticsRoute: RecommendationAnalyticsRoute,
  ReferralsRoute: ReferralsRoute,
  SearchMgmtRoute: SearchMgmtRoute,
  SecurityRoute: SecurityRoute,
  SeoRoute: SeoRoute,
  StorageRoute: StorageRoute,
  SubscriptionsRoute: SubscriptionsRoute,
  SuccessStoriesRoute: SuccessStoriesRoute,
  SupportRoute: SupportRoute,
  SystemConfigRoute: SystemConfigRoute,
  VerificationRoute: VerificationRoute,
  WalletRoute: WalletRoute,
  UsersUserIdRoute: UsersUserIdRoute,
  UsersIndexRoute: UsersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
